import hashlib
import logging
import secrets
import uuid

from django.core.cache import cache
from django.db import models, transaction

logger = logging.getLogger(__name__)

from stapel_core.access import access
from stapel_core.django.models import RevisionMixin

from stapel_translate.conf import get_default_language
from stapel_translate.utils import get_cache_key


class AuthorizedTranslator(models.Model):
    """Authorized translator allowed to access the dashboard."""
    email = models.EmailField(unique=True, db_index=True)
    name = models.CharField(max_length=255, blank=True, default='')
    allowed_languages = models.JSONField(
        default=list, blank=True,
        help_text="List of language codes this translator can edit. Empty = all languages."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Authorized Translator"
        verbose_name_plural = "Authorized Translators"


class TranslationEntry(RevisionMixin, models.Model):
    key = models.CharField(max_length=255, unique=True)
    comment = models.TextField(blank=True, default='')
    translator_comment = models.TextField(blank=True, default='', help_text="Notes from translator")
    refs = models.JSONField(default=list, blank=True, help_text="Admin URLs referencing this key")
    screenshot = models.FileField(upload_to='screenshots/', blank=True, null=True, help_text="Screenshot of Figma screen where this key is used")

    source = models.CharField(max_length=100, blank=True, default='')
    order = models.IntegerField(null=True, blank=True, db_index=True)
    llm_translated = models.BooleanField(default=False, help_text="Whether this translation was generated by LLM")

    # ------------------------------------------------------------------
    # Per-language values live in TranslationValue (related_name="values").
    # ------------------------------------------------------------------

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.refresh_cached_entry()

    def bump_revision(self):
        """Bump this entry's revision (RevisionMixin semantics) via UPDATE.

        Used when a TranslationValue row changes: the entry row itself is
        untouched except for the monotonically increasing revision, so
        clients syncing by revision pick up per-language changes.
        """
        if self.pk is None:
            return
        cls = type(self)
        with transaction.atomic():
            max_revision = cls.objects.aggregate(
                max_rev=models.Max('revision')
            )['max_rev'] or 0
            self.revision = max_revision + 1
            cls.objects.filter(pk=self.pk).update(revision=self.revision)

    # -- per-language value helpers ------------------------------------

    def _value_rows(self):
        """{language: TranslationValue} — uses prefetched rows when present."""
        if not hasattr(self, "_values_cache"):
            self._values_cache = {v.language: v for v in self.values.all()}
        return self._values_cache

    def invalidate_values_cache(self):
        self.__dict__.pop("_values_cache", None)

    def refresh_cached_entry(self):
        """Re-store this entry (with warm value rows) in the shared cache."""
        self.invalidate_values_cache()
        if self.pk is not None:
            self._value_rows()  # prewarm so cached copies carry the values
        cache.set(get_cache_key(self.key), self, timeout=None)

    def get_value(self, lang):
        """Return the stored value for *lang*, or None if absent."""
        row = self._value_rows().get(lang)
        return row.value if row is not None else None

    def get_verified(self, lang) -> bool:
        """Return the verified flag for *lang* (False if no value row)."""
        row = self._value_rows().get(lang)
        return row.verified if row is not None else False

    def set_value(self, lang, value=None, verified=None):
        """Create/update the TranslationValue row for *lang*.

        ``value=None`` / ``verified=None`` leave that aspect unchanged
        (new rows default to ``""`` / ``False``). Saving the row bumps this
        entry's revision and refreshes the shared cache.
        """
        defaults = {}
        if value is not None:
            defaults["value"] = value
        if verified is not None:
            defaults["verified"] = verified
        row, _created = TranslationValue.objects.update_or_create(
            entry=self, language=lang, defaults=defaults
        )
        rows = self.__dict__.get("_values_cache")
        if rows is not None:
            rows[lang] = row
        return row

    def values_dict(self, include_empty=False):
        """{language: value} for all stored rows (non-empty by default)."""
        return {
            lang: row.value
            for lang, row in self._value_rows().items()
            if include_empty or row.value
        }

    @property
    def en(self):
        """English value (read-only convenience; use set_value to write)."""
        return self.get_value('en')

    def get(self, lang=None):
        lang = lang or get_default_language()
        return (
            self.get_value(lang)
            or self.get_value(get_default_language())
            or self.key
        )

    def __str__(self):
        return f"{self.key} [{self.get_value('en') or self.get_value('ru') or 'no EN/RU'}]"

    class Meta:
        verbose_name = "Translation"
        verbose_name_plural = "Translations"


class TranslationValue(models.Model):
    """A single language's value for a TranslationEntry (row per language)."""

    entry = models.ForeignKey(
        TranslationEntry,
        on_delete=models.CASCADE,
        related_name='values',
    )
    language = models.CharField(max_length=10, db_index=True)
    value = models.TextField(blank=True, default='')
    verified = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Translation Value"
        verbose_name_plural = "Translation Values"
        constraints = [
            models.UniqueConstraint(
                fields=['entry', 'language'],
                name='translate_value_unique_entry_language',
            ),
        ]

    def save(self, *args, **kwargs):
        value_changed = bool(self.value) if self.pk is None else None
        if self.pk is not None:
            old_value = (
                type(self).objects.filter(pk=self.pk)
                .values_list('value', flat=True)
                .first()
            )
            value_changed = old_value != self.value
        super().save(*args, **kwargs)
        entry = self.entry
        entry.bump_revision()
        entry.refresh_cached_entry()
        if value_changed:
            from stapel_translate.events import emit_translations_changed
            emit_translations_changed(  # emit-check: ok — this row is already saved; emit_translations_changed() opens its OWN transaction.atomic() savepoint around the actual emit() and never lets a broker/outbox failure propagate (see its docstring) — a lexical false positive, the checker can't see the callee's internal atomic block
                self.language, [entry.key],
            )

    def delete(self, *args, **kwargs):
        entry = self.entry
        result = super().delete(*args, **kwargs)
        entry.bump_revision()
        entry.refresh_cached_entry()
        return result

    def __str__(self):
        return f"{self.entry.key} [{self.language}]"


@access.ops  # append-only audit log — admin already forbids add/change (admin-suite AS-5)
class TranslationHistory(models.Model):
    """History of translation changes."""
    CHANGE_TYPE_CHOICES = [
        ('translation', 'Translation'),
        ('verification', 'Verification'),
    ]

    entry = models.ForeignKey(
        TranslationEntry,
        on_delete=models.CASCADE,
        related_name='history'
    )
    language = models.CharField(max_length=5)
    change_type = models.CharField(max_length=20, choices=CHANGE_TYPE_CHOICES)
    old_value = models.TextField(blank=True, null=True)
    new_value = models.TextField(blank=True, null=True)
    author_email = models.EmailField(blank=True, null=True, db_index=True)
    author_name = models.CharField(max_length=255, blank=True, default='')
    source = models.CharField(max_length=50, default='dashboard')  # 'dashboard', 'admin', 'llm'
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return f"{self.entry.key} [{self.language}] by {self.author_email or 'system'}"

    class Meta:
        verbose_name = "Translation History"
        verbose_name_plural = "Translation History"
        ordering = ['-created_at']


@access.secret  # hashed Figma-plugin API key carrier (admin-suite AS-5)
class FigmaApiKey(models.Model):
    """API key for Figma plugin authentication.

    The plaintext key ("fk_" + token) is generated once on creation, exposed
    via the one-time ``plaintext_key`` attribute, and never stored — only its
    SHA-256 hash and an 8-char prefix (for lookup/display) are persisted.
    """

    KEY_PREFIX_LENGTH = 8

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, help_text="Name to identify this key (e.g., 'Design Team')")
    key_hash = models.CharField(max_length=64, unique=True, editable=False, default='')
    prefix = models.CharField(max_length=8, editable=False, default='', db_index=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(blank=True, null=True)

    # One-time attribute holding the plaintext key right after generation.
    plaintext_key = None

    @staticmethod
    def generate_key() -> str:
        return "fk_" + secrets.token_urlsafe(32)

    @staticmethod
    def hash_key(raw_key: str) -> str:
        return hashlib.sha256(raw_key.encode("utf-8")).hexdigest()

    def save(self, *args, **kwargs):
        if not self.key_hash:
            raw_key = self.generate_key()
            self.key_hash = self.hash_key(raw_key)
            self.prefix = raw_key[: self.KEY_PREFIX_LENGTH]
            # Shown exactly once — never persisted.
            self.plaintext_key = raw_key
        super().save(*args, **kwargs)

    @classmethod
    def authenticate(cls, raw_key: str):
        """Return the matching active key, or None.

        Lookup by prefix, then constant-time hash comparison.
        """
        import hmac

        if not raw_key:
            return None
        candidate_hash = cls.hash_key(raw_key)
        candidates = cls.objects.filter(
            prefix=raw_key[: cls.KEY_PREFIX_LENGTH], is_active=True
        )
        for key_obj in candidates:
            if key_obj.key_hash and hmac.compare_digest(candidate_hash, key_obj.key_hash):
                return key_obj
        return None

    def __str__(self):
        return f"{self.name} ({self.prefix or str(self.id)[:8]}...)"

    class Meta:
        verbose_name = "Figma API Key"
        verbose_name_plural = "Figma API Keys"
