# Generated by Django 5.2.8 on 2025-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('en', models.CharField(blank=True, null=True, verbose_name='English')),
                ('ru', models.CharField(blank=True, null=True, verbose_name='Russian')),
                ('de', models.CharField(blank=True, null=True, verbose_name='German')),
                ('fr', models.CharField(blank=True, null=True, verbose_name='French')),
                ('es', models.CharField(blank=True, null=True, verbose_name='Spanish')),
                ('it', models.CharField(blank=True, null=True, verbose_name='Italian')),
                ('pt', models.CharField(blank=True, null=True, verbose_name='Portuguese')),
                ('verified', models.BooleanField(default=False)),
                ('source', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
    ]
