# Generated by Django 5.2.8 on 2026-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='revision',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
