# Generated by Django 5.2.8 on 2026-01-01 19:27
#
# stapel: contract-phase
# verified: this migration shipped in the pre-release development window —
# commit 461ccc3 ("initial: stapel-translate") bundles migrations 0001-0011+
# together and is the repo's first commit; no version of stapel-translate
# was ever released (first tag v0.2.0) without this migration already
# applied. Data is copied from the old `verified` field to the new
# per-language *_verified fields via RunPython before RemoveField runs.

from django.db import migrations, models


def migrate_verified_to_per_language(apps, schema_editor):
    """Copy old verified value to all per-language verified fields."""
    TranslationEntry = apps.get_model('translate', 'TranslationEntry')
    TranslationEntry.objects.filter(verified=True).update(
        en_verified=True,
        ru_verified=True,
        de_verified=True,
        fr_verified=True,
        es_verified=True,
        it_verified=True,
        pt_verified=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_add_revision_to_translation'),
    ]

    operations = [
        # First add new fields
        migrations.AddField(
            model_name='translationentry',
            name='en_verified',
            field=models.BooleanField(default=False, verbose_name='English verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ru_verified',
            field=models.BooleanField(default=False, verbose_name='Russian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='de_verified',
            field=models.BooleanField(default=False, verbose_name='German verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='fr_verified',
            field=models.BooleanField(default=False, verbose_name='French verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='es_verified',
            field=models.BooleanField(default=False, verbose_name='Spanish verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='it_verified',
            field=models.BooleanField(default=False, verbose_name='Italian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='pt_verified',
            field=models.BooleanField(default=False, verbose_name='Portuguese verified'),
        ),
        # Migrate data
        migrations.RunPython(migrate_verified_to_per_language, migrations.RunPython.noop),
        # Remove old field
        migrations.RemoveField(
            model_name='translationentry',
            name='verified',
        ),
    ]
