# Generated by Django 5.2.8 on 2026-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_replace_verified_with_per_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='ar',
            field=models.CharField(blank=True, null=True, verbose_name='Arabic'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ar_verified',
            field=models.BooleanField(default=False, verbose_name='Arabic verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='he',
            field=models.CharField(blank=True, null=True, verbose_name='Hebrew'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='he_verified',
            field=models.BooleanField(default=False, verbose_name='Hebrew verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='hi',
            field=models.CharField(blank=True, null=True, verbose_name='Hindi'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='hi_verified',
            field=models.BooleanField(default=False, verbose_name='Hindi verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='hu',
            field=models.CharField(blank=True, null=True, verbose_name='Hungarian'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='hu_verified',
            field=models.BooleanField(default=False, verbose_name='Hungarian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ja',
            field=models.CharField(blank=True, null=True, verbose_name='Japanese'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ja_verified',
            field=models.BooleanField(default=False, verbose_name='Japanese verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ko',
            field=models.CharField(blank=True, null=True, verbose_name='Korean'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='ko_verified',
            field=models.BooleanField(default=False, verbose_name='Korean verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='lb',
            field=models.CharField(blank=True, null=True, verbose_name='Luxembourgish'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='lb_verified',
            field=models.BooleanField(default=False, verbose_name='Luxembourgish verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='pl',
            field=models.CharField(blank=True, null=True, verbose_name='Polish'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='pl_verified',
            field=models.BooleanField(default=False, verbose_name='Polish verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='sh',
            field=models.CharField(blank=True, null=True, verbose_name='Serbo-Croatian'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='sh_verified',
            field=models.BooleanField(default=False, verbose_name='Serbo-Croatian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='tr',
            field=models.CharField(blank=True, null=True, verbose_name='Turkish'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='tr_verified',
            field=models.BooleanField(default=False, verbose_name='Turkish verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='uk',
            field=models.CharField(blank=True, null=True, verbose_name='Ukrainian'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='uk_verified',
            field=models.BooleanField(default=False, verbose_name='Ukrainian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='zh',
            field=models.CharField(blank=True, null=True, verbose_name='Mandarin'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='zh_verified',
            field=models.BooleanField(default=False, verbose_name='Mandarin verified'),
        ),
    ]
