from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_add_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='llm_translated',
            field=models.BooleanField(default=False, help_text='Whether this translation was generated by LLM'),
        ),
    ]
