# Generated by Django 5.2.8 on 2026-02-05 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0008_alter_translationentry_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('change_type', models.CharField(choices=[('translation', 'Translation'), ('verification', 'Verification')], max_length=20)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('author_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='dashboard', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='translate.translationentry')),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation History',
                'ordering': ['-created_at'],
            },
        ),
    ]
