# Generated by Django 5.2.8 on 2026-02-05 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0009_translationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigmaApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name to identify this key (e.g., 'Design Team')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Figma API Key',
                'verbose_name_plural': 'Figma API Keys',
            },
        ),
    ]
