# Generated by Django 5.2.8 on 2026-02-07 12:21
#
# stapel: contract-phase
# verified: this migration shipped in the pre-release development window —
# commit 461ccc3 ("initial: stapel-translate") is the repo's first commit and
# bundles migrations 0001-0011+ together; no version of stapel-translate was
# ever released (first tag v0.2.0) without this migration already applied.
# `sh` (Serbo-Croatian) was a since-abandoned language column with no
# consuming release.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0010_figma_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationentry',
            name='sh',
        ),
        migrations.RemoveField(
            model_name='translationentry',
            name='sh_verified',
        ),
    ]
