# Generated by Django 5.2.8 on 2026-02-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0010_figma_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationentry',
            name='sh',
        ),
        migrations.RemoveField(
            model_name='translationentry',
            name='sh_verified',
        ),
    ]
