# Generated by Django 5.2.8 on 2026-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0011_remove_serbo_croatian'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='hr',
            field=models.CharField(blank=True, null=True, verbose_name='Croatian'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='hr_verified',
            field=models.BooleanField(default=False, verbose_name='Croatian verified'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='sr',
            field=models.CharField(blank=True, null=True, verbose_name='Serbian'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='sr_verified',
            field=models.BooleanField(default=False, verbose_name='Serbian verified'),
        ),
    ]
