# Generated by Django 5.2.8 on 2026-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0012_add_serbian_croatian'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationentry',
            name='refs',
            field=models.JSONField(blank=True, default=list, help_text='Admin URLs referencing this key'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='translator_comment',
            field=models.TextField(blank=True, default='', help_text='Notes from translator'),
        ),
        migrations.AlterField(
            model_name='translationentry',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
