# Generated by Django 5.2.8 on 2026-02-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0014_translationentry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedtranslator',
            name='allowed_languages',
            field=models.JSONField(blank=True, default=list, help_text='List of language codes this translator can edit. Empty = all languages.'),
        ),
        migrations.AddField(
            model_name='authorizedtranslator',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
